### ISSUE TITLE
Addition 

### ISSUE THREAD

**Issue by mmachel** [mmachel/Basics#2]
Add some things of IT.

**Comment by LisaGraefe** [comment]
Hello. I joined your group for the exercises for the C#-Course. Sorry that it was relatively late. Have you already completed the tasks?

**Comment by mmachel** [comment]
Quoting LisaGraefe <notifications@github.com>:

> Hello. I joined your group for the exercises for the C#-Course.  
> Sorry that it was relatively late. Have you already completed the  
> tasks?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mmachel/Basics/issues/2#issuecomment-617171665

Hello. I planed to start today in the evening or tomorrow with  
Aufgabe01. And you?

**Comment by LisaGraefe** [comment]
I've started with Aufgabe_00 but I only came until 9.
Did you do this?

**Comment by LisaGraefe** [comment]
Tomorrow is the first exercise so i wanted to do something before that.

Can we write on Whatsapp or something else?

**Comment by mmachel** [comment]
Quoting LisaGraefe <notifications@github.com>:

> I've started with Aufgabe_00 but I only came until 9.
> Did you do this?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mmachel/Basics/issues/2#issuecomment-617208981

I did'nt do all tasks, I left some. Maybe I am going to do them today  
after classes. I did some tasks like pgf_gen of the task 10 & 11 on my  
repo. Which Text-editor do u use?

**Comment by mmachel** [comment]
Quoting LisaGraefe <notifications@github.com>:

> Tomorrow is the first exercise so i wanted to do something before that.
>
> Can we write on Whatsapp or something else?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mmachel/Basics/issues/2#issuecomment-617210428


No problem,we can write. My whatsapp nr: 015237154815
